#page title
page_title                                : Energetic Bubble app                      # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://link_to_play_store.com                                          # Enter Google Play Store URL.
presskit_download_link                    : https://energeticbubble.com               # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/Logo-512.png # assets/appicon.png      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_favicon                               : assets/favicon.ico
app_name                                  : Energetic Bubble                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Energetic bubble
app_horizontal                            : assets/logo_only_text.png
app_logo_horizontal                       : assets/logo_only_text_220px-width.png

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Energetic Bubble                                
your_link                                 : https://energeticbubble.com                     
your_city                                 : Love                                
email_address                             : hello@energeticbubble.com
facebook_username                         :                                           
instagram_username                        :
twitter_username                          :
github_username                           :
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : MyEnergeticPathway
    description                           : Photo based scan your personal profile read out
    icon_name                             : assets/logo-brown-50-80.png
    
  - title                                 : Who do we serve?
    description                           : Interest in energetic well being
    icon_name                             : assets/logo-red-50-80.png

  - title                                 : How does it work
    description                           : Designed to read your Energetic Self
    icon_name                             : assets/logo-blue-50-80.png

  - title                                 : What do I get?
    description                           : Variety of outputs
    icon_name                             : assets/logo-yellow-50-80.png

  - title                                 : What are the timelines?
    description                           : Two business days return
    icon_name                             : assets/logo-green-50-80.png
  
  - title                                 : What are the costs?
    description                           : Value for money
    icon_name                             : assets/logo-blue-50-80.png

  - title                                 : Terms & conditions
    description                           : Privacy and confidentiality
    icon_name                             : assets/logo-orange-50-80.png


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
